name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Build (uses Gradle 8.9 from action)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.9

      - name: Assemble debug
        run: gradle --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
